### ISSUE TITLE
FR: Split Messaging

### ISSUE THREAD

**Issue by cemo** [firebase/firebase-admin-java#238]
We have million users and topics on firebase. However sending some general push notifications to all users is causing over load. It would be very nice to have a parameter to send messages in an interval. For example for 10M users in a topic, If I send 10 minute for messaging interval, I expect 1M users per minute. This is nice since the load is distributed.

**Comment by hiranya911** [comment]
Are all 10M users on the same topic? Then you are essentially sending just one message to the topic, which FCM sends out to all topic subscribers. Where do you see the overload in this flow?

**Comment by cemo** [comment]
Firebase and FCM can handle to send these pushes so fast but this is not valid in server side. Our backend systems have issues to handle so much users in short amount time especially if the message is sent to all users.

**Comment by hiranya911** [comment]
What does your server-side code look like (some psuedocode is good enough for us to get an idea of your use case)? Is it something like this:

```
List<String> reallyLargeTokensList = .... ;
for (String token : reallyLargeTokensList) {
  sendFCMNotification(token);
}
```

**Comment by cemo** [comment]
Our use case includes creating some segments on our server side. These segments are synced firebase via topics. We send notifications to these topics. 

```
List<String> userIds = createUserLists(criteria); // thousands users
String topicName = createTopic(campaignName);
Boolean isSuccess = sychUsers(topicName, userIds);
sendNotification(topicName, message)
```

**Comment by hiranya911** [comment]
So what exactly is the source of overload in the above code? Is it the sync operation where you have to bulk subscribe users to a topic? `sendNotification()` should be pretty fast, since it's just one HTTP call to the FCM server.

**Comment by cemo** [comment]
`sendNotification` is fast. However these notified users are immediately sending requests to our servers. Sometimes the number of these users are much more than we can handle. We would like to receive these requests by time not so fast.

**Comment by hiranya911** [comment]
I will assign this to the FCM team for some feedback. But personally I don't think this is something that FCM should implement.

Topic messaging systems (FCM included) are generally optimized for scale and throughput. Developers use topic messaging _because_ it is capable of delivering messages to a very large number of users, very quickly.  Implementing throttling on top of that is counter to those goals. This is why most topic messaging systems don't expose such settings. See this similar discussion on [AWS forums](https://forums.aws.amazon.com/thread.jspa?messageID=751105). SNS seems to implement a max receive rate setting, but that is per subscriber.

Also it seems you're trying to throttle your incoming requests by throttling the FCM outgoing throughput. That doesn't feel architecturally sound. If you ever change your notification mechanism, you will have to solve this problem all over again. You will also have to keep revising your notification intervals as your user base grows. Instead, perhaps you should consider one of the following solutions:

1. Implement throttling yourself: Group your users into `N` buckets, and create separate topics for each bucket. This way you have total and explicit control over number of users per bucket, and the notification delay between different topics. You can just create new buckets as new users sign up to the app.
2. Implement a random delay mechanism at the client-side, so that all of them don't contact your servers at the same time.
3. Implement your servers on top of a more elastic infrastructure like Cloud Functions, that can absorb large load spikes easily.

**Comment by hiranya911** [comment]
I would create a cloud function to handle subscriptions. Suppose you want no more than 100,000 users per bucket, and you already have 280,000 users. You can represent this state in the database (Firestore or RTDB) using the following structure:

```
{
  "topic-0": 100000,
  "topic-1": 100000,
  "topic-2": 80000
}
```

Now you can implement an [`onCreate()` trigger](https://firebase.google.com/docs/functions/auth-events#trigger_a_function_on_user_creation) which does the following in a transaction:
1. Find the topic with the largest index (topic-2 in the above case).
2. If the count is less than 100,000 increment count and subscribe the user to that topic.
3. Else create a new topic with count 1 (`topic-3: 1`), and subscribe the user to the new topic.

Now your sender logic becomes:
```
List<String> topics = findTopicsFromDatabase();
for (String topic : topics) {
  sendToTopic(topic);
  delay();
}
```

**Comment by cemo** [comment]
@hiranya911 I appreciate your help but this seems only a workaround. There are some edge cases like sending "all users". The required users are actually available on Firebase but we need to send again on servers again. 

I really believe that currently there is 2 essential feature need to be addressed. One of them is this issue and the other one is scheduled messages on API #236.

**Comment by cemo** [comment]
@chong-shao is there any news on this topic?

**Comment by chong-shao** [comment]
Hi cemo, for our current infrastructure it's not very straightforward to enable this. But a solution is under discussion.

**Comment by Lordofcodes** [comment]
@chong-shao  @cemo  @hiranya911 I am facing the same problem. I sent a common message to a topic `All`. 
After sending the notification our backend API stops to respond, or takes too much time to respond.

**Comment by hiranya911** [comment]
@Lordofcodes please file a feature request at https://firebase.google.com/support

**Comment by Lordofcodes** [comment]
> Firebase and FCM can handle to send these pushes so fast but this is not valid in server side. Our backend systems have issues to handle so much users in short amount time especially if the message is sent to all users.

@cemo  Can you describe why is this happening. Is it because your server gets a lot of request in very short span of time as all user will open the notification? Or something else?

**Comment by cemo** [comment]
@Lordofcodes I have missed this sorry. Yes we have around 5M active users. In case a bulk send operation it is causing a lot of requests in very short time. In a peak time we have 2-3 times more load for our servers however in case a bulk push message like targeting all of our users load is increasing up to 10 times more.
