### ISSUE TITLE
Provide Token Validation Errors list

### ISSUE THREAD

**Issue by feinstein** [firebase/firebase-admin-java#277]
Reading the docs [here](https://firebase.google.com/docs/auth/admin/errors) for Firebase Auth Errors, one can assume those error codes for the node.js library would be the same returned in the Firebase Admin Java library as well, but looking into the source code I can't find those strings anywhere.

I am using Firebase Auth in my server to validate REST Endpoint requests, so I need to return proper UNAUTHORIZED 401 codes, convening a message such as `The access token expired`, `The access token is invalid` or `The access token is revoked`, so the client knows what action to take.

The node.js library has:
```
auth/id-token-expired
auth/id-token-revoked
```

Whereas on the source code of this Java library I can only find a generic `ERROR_INVALID_CREDENTIAL`.

Where can I find those error codes in this library?

How can I communicate to my client if his token has expired and he needs a new one, or if it was revoked and he should contact customer service?

**Comment by hiranya911** [comment]
Java SDK only uses following error codes with respect to this functionality:

* ERROR_INVALID_CREDENTIAL (used for both invalid and expired tokens)
* ERROR_RUNTIME_EXCEPTION (if an unexpected error occurs during verification)
* id-token-revoked (token has been explicitly revoked)

The `auth/` prefixed error codes were only ever supported in the Node.js SDK. In general we are working towards decommissioning all these existing error codes, and moving towards a new unified error handling mechanism across all languages. 

In the meantime, if you wish to distinguish between expired and otherwise invalid tokens, you will have to look at the error message (I know, it's not not pretty). The expired tokens raise an error message of the form `Firebase %s has expired or is not yet valid. Get a fresh %s and try again.`

**Comment by feinstein** [comment]
I see, well then please make those error codes comply with the OAuth 2.0 error codes, as described in section 3.1 here:

http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html

**Comment by feinstein** [comment]
Also, could you leave this issue open until the new error codes arrive? This way I will be notified when I can update my code with them.

**Comment by hiranya911** [comment]
This is a large scale breaking change that will be released as a major version. All developers will have to upgrade and change their code when it's eventually released.

As for the OAuth2 spec, I don't see how that's related to our SDK. Error codes and error handling guidelines for Firebase/GCP products are laid out here: https://cloud.google.com/apis/design/errors. Our new error handling mechanism will be based on that.

**Comment by feinstein** [comment]
I am just saying that since Firebase Auth deals with Token Authentication/Authorization, it would be nice to have all the error codes that OAuth 2.0 speaks about, which is mostly "token expired, revoked, malformed, or invalid for other reasons". So we can map those errors to a proper 401 Response body. But ultimately I think that only expired, revoked and invalid is enough.
