### ISSUE TITLE
maven artifact uses 4 month old firestore dependency

### ISSUE THREAD

**Issue by AbhishekChugh** [firebase/firebase-admin-java#323]
### Describe your environment

  * Operating System version: ubuntu 18.04
  * Firebase SDK version: com.google.firebase:firebase-admin:6.10.0
  * Library version: *What's this?*
  * Firebase Product: firestore

### Describe the problem
The firestore artifact used by the admin SDK is 4 months old (1.9.0) and is missing many updates.
Please update to latest version (1.28.0).

I am specifically interested in https://github.com/googleapis/google-cloud-java/issues/5622

**Comment by AbhishekChugh** [comment]
![download](https://user-images.githubusercontent.com/5623836/67441647-54470080-f61b-11e9-8e9e-68e7d08a3ee1.png)

**Comment by AbhishekChugh** [comment]
@hiranya911

**Comment by hiranya911** [comment]
Feel free to provide a pull request. Otherwise somebody here will eventually bump the dependency version.

But this shouldn't block you from using the latest Firestore version. Just declare a direct dependency on latest google-cloud-firestore. Dependency managers like Maven give high priority to direct dependencies, so the version you specify will be installed.

**Comment by AbhishekChugh** [comment]
Thanks so much @hiranya911. Didnt know compile dependency version could be overriden. 

Btw, in https://github.com/firebase/firebase-admin-java/blob/master/pom.xml, 
the version is already updated to 1.21.0 for google-cloud-firestore. Someone just needs to create the new artifact.

**Comment by achuinard** [comment]
Need this updated to 1.31.0 to get IN queries.
