### ISSUE TITLE
FR: Add the fields 'email' and 'credential' to FirebaseAuthUserCollisionException

### ISSUE THREAD

**Issue by nico1510** [firebase/firebase-admin-java#36]
### [READ] Step 1: Are you in the right place?

  * No I'm not sorry :( This issue should ideally be opened in the android SDK repo but this isn't on Github yet so feel free to close it or move it as you like.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: android
  * Firebase SDK version: 10.2.6
  * Firebase Product: auth

### [REQUIRED] Step 3: Describe the problem

I implemented the sign in flow which is described here: https://firebase.google.com/docs/auth/web/facebook-login (see point *Handling account-exists-with-different-credential Errors*).

If a user tries to sign up with an email which is already used in an account of a different provider, he is offered to link his accounts. This works well for the web SDK.

When I tried to do the same with the android SDK I noticed that the error object `FirebaseAuthUserCollisionException` provides no information about which email it is that is already used. That makes it impossible to handle `account-exists-with-different-credential` errors with the android SDK.

I implemented the same with the iOS SDK and even though there the credential is not attached to the corresponding `FIRAuthErrorCodeEmailAlreadyInUse` object, at least the email address is. The credential can be stored by the developer and retrieved from elsewhere s.t. the error can be dealt with in iOS too. 

Only in android a developer has no chance to know which email address is duplicate and therefore you can't even let the user know and have to display a generic error message like 'email address is already in use' which leads to poor usability in my opinion.

#### Steps to reproduce:

1. create a user account with google
2. try to sign in a user with facebook with the same email address as in 1.
3. `FirebaseAuthUserCollisionException` should be thrown and the email address can't be retrieved

**Comment by hiranya911** [comment]
I will route this to the appropriate developers, and close it. Thanks for the bud report.

**Comment by malcolmdeck** [comment]
Hello! Malcolm here, an Android dev the Firebase Auth team :smiley: 

Having talked with the folks that develop the iOS SDK, the email is never populated as part of the FIRAuthErrorCodeEmailAlreadyInUse response for the current release (nor for any release since January of this year - I didn't check before that). So the iOS and Android SDKs are functionally equivalent. 

However, your request is a useful one regardless, and we'll look into providing that information in the future. For now, the email can be retrieved from the Facebook SDK using a GraphRequest, as outlined in the top-level response here:
https://stackoverflow.com/questions/29295987/android-facebook-4-0-sdk-how-to-get-email-date-of-birth-and-gender-of-user

I know that that's not the easiest of solutions, but I hope that helps!

~Malcolm

**Comment by nico1510** [comment]
Hi @malcolmdeck thanks for responding I did not have much hope :smile: 
I never implemented it in iOS but read it in the docs [here](https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Constants#/c:@FIRAuthErrorUserInfoEmailKey) that you can get the email there so I just assumed it was possible.
Anyway thanks for adding it to your feature requests and in the meantime I can use your workaround.
