### ISSUE TITLE
Security issue: User password is stored as String in UserRecord request classes

### ISSUE THREAD

**Issue by medvedev** [firebase/firebase-admin-java#403]
* Library version: 6.12.2
  * Firebase Product: auth

**Problem**:  
`UserRecord.CreateRequest` and `UserRecord.UpdateRequest` classes store password as String ([source link](https://github.com/firebase/firebase-admin-java/blob/v6.12.2/src/main/java/com/google/firebase/auth/UserRecord.java#L394)).  
Java String is known as a bad way to store sensitive data, like passwords for following reasons:  
1. Password can easily leak to log as part of `toString()`
2. Developer has no way to erase it from memory immediately after use, i.e. user passwords live in heap for an uncontrolled amount of time.  

**Suggestion**, assuming that Firebase API can accept password as `char[]`:  
  
Mark current getter and setter of password under UserRecord.CreateRequest and UserRecord.UpdateRequest as deprecated and implement new getter and setter for `char[]` password representation.

**Comment by hiranya911** [comment]
Thanks @medvedev. My take on this issue is that this is not a problem most of the time. And in the very rare occasions where this can be a problem, a simple API change cannot guard against it. Here's my reasoning:

* Neither `CreateRequest` nor `UpdateRequest` implement the `toString()` method, so (1) does not apply.
* (2) could be a problem only if the runtime has been compromised to such a degree that an attacker has direct access to memory. In such a situation, keeping the password as `char[]` is not going to do a whole lot of good. After all `String` type also stores the actual characters in a `char[]`. This sort of attacks should be prevented at the operational/deployment level, rather than at the runtime level.

The other reason why this is generally not a problem is that the SDK does not actually "store" passwords in memory beyond the `createUser()` or `updateUser()` operations they was intended for. Once the respective operation is complete, SDK releases all references to these objects, which allows the garbage collector to reclaim them. Yes, the developer has no control over when they will get reclaimed, but unless the developer is leaking their references, these objects should get reclaimed shortly after the intended operation is done. Modern generational garbage collectors reclaim short-lived, untenured objects rather aggressively.

Then there's also the issue that the backend API for these operations expect the password to be passed in as a plaintext string (it is sent in a JSON object over HTTPS). So even if we accept the password in some other format, the SDK still need to construct the plaintext string at some point during the request marshalling process. These strings will then also reside in memory, and will have more or less the same lifecycle as a String passed in by the developer.

So my advise would be to consider the risk of this API to be pretty minimal, granted the code is deployed in a secure environment and the code doesn't leak references. If you do have any evidence to contrary, please do share them with us. If it continues to bother you also look at other options for setting a user's password like:

* changing it from the client SDK, or
* using the `importUsers()` API which allows specifying a password hash+salt combo (which is the proper way of masking a password during transit and at rest).

**Comment by medvedev** [comment]
Thanks for such a detailed response @hiranya911 
Let me advocate my opinion.

> Neither CreateRequest nor UpdateRequest implement the toString() method, so (1) does not apply.

This is partially true. Since both firebase user requests accept password as String, they force users of the library to store password as an instance of String. So, while the library classes do not implement `toString()` itself, they increase probability of password being accidentally logged by user's code.

> (2) could be a problem only if the runtime has been compromised to such a degree that an attacker has direct access to memory. In such a situation, keeping the password as char[] is not going to do a whole lot of good. After all String type also stores the actual characters in a char[]. This sort of attacks should be prevented at the operational/deployment level, rather than at the runtime level.

Attacker might also have access to memory dump, which is more common thing. The difference between `char[]` and `String` for me as for a developer who cares about security is: With password stored as a `char[]` I can erase array directly in the memory, at any point of time. This is how at least some of other security-related libraries work internally. ([example1](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/pqc/crypto/sphincs/SPHINCS256Signer.java#L306-L311),[example2](https://github.com/phxql/argon2-jvm/blob/v2.7/src/main/java/de/mkammerer/argon2/BaseArgon2.java#L75))

[Oracle Security coding guide](https://www.oracle.com/technetwork/java/seccodeguide-139067.html) does not explicitly forbid use of strings, but instead recommends to use char arrays or other mutable structures to store sensitive date:
> **Guideline 2-2**:
...
Some transient data may be kept in mutable data structures, such as char arrays, and cleared immediately after use.
...

Currently users of Firebase admin library are forced to break this recommendation.

> Modern generational garbage collectors reclaim short-lived, untenured objects rather aggressively.

This point makes sense, but still most (or all) JVM implementations do not provide any time guarantees for clearing such objects. If user's code is poorly designed, then in runtime password string might be moved to a "old gen" space (or whatever it's being called now), and be available to the potential attacker for even longer time.

> Then there's also the issue that the backend API for these operations expect the password to be passed in as a plaintext string

Then my assumption in the issue's description is wrong. Maybe, it's still possible to request backend API to provide a different endpoints, accepting passwords as char arrays? This does not sound like a huge effort.

>  If it continues to bother you also look at other options for setting a user's password like:

    changing it from the client SDK, or
    using the importUsers() API which allows specifying a password hash+salt combo (which is the proper way of masking a password during transit and at rest).

Using client SDK is a good option, but it does not let my custom backend to create\update user with a password in a secure way
`importUsers()` might work for creating new records, but does not allow update of existing ones.

As a bottom line, I still think that the issue I've described should be addressed by adding new endpoint to backend API and updating library API. It's up to you to agree with me or not, and set right priority for this issue, of course.

**Comment by hiranya911** [comment]
I'll comment on some of the points made here. But the TLDR is that both the backend and SDK APIs have already gone through Google security review, and any risks have been deemed minimal for the use of this API. So a new API endpoint is unlikely to happen.

I still don't see changing the API signature from `String` to `char[]` as a reasonable solution to the problems you've outlined. At best it's a half measure. Here's why:

1. The developer may still store the password as a `String` out of convenience. In fact this is extremely likely with the type of use cases where the Admin SDK gets used, since the password will often reach the application in the form of a web request (json or form encoded) or some other type of user input. Most input marshalling/unmarshalling APIs would simply parse the incoming value as a String.

2. The developer is still on the hook for not logging the password array contents, and making sure the array gets cleared after use. If a memorydump is taken just before the array is cleared and that gets exposed, you still have the same problem. The Oracle security guidelines also state the following which are relevant here:

```
Clearing data structures has reduced effectiveness on typical Java 
runtime systems as objects are moved in memory transparently to 
the programmer....
```
```
....As an example, a low-level string parsing library may log the text 
it works on. An application may parse an SSN with the library. This 
creates a situation where the SSNs are available to administrators 
with access to the log files.
```

So the onus of making sure something doesn't accidentally leak is still very much on the developer, even if the SDK accepts passwords as `char[]`.

3. The only meaningful way to address the issues you've pointed out is to not accept plaintext passwords at all (i.e. only ever accept a hash). But this is unfortunately not possible with this particular API at the moment.

 One thing we can do is to provide a `clear()` method on the `CreateRequest` and `UpdateRequest` types, so the developer can clear the underlying Map after use. I'm not convinced that it makes the API more secure than it already is, but it does give the developer some additional control over the lifespan of sensitive data kept in memory, which is better than what the non-deterministic GC provides.

If you feel strongly about solving this via a new endpoint (or possibly by adding hash support to the existing endpoint), I'd recommend you to file a feature request at https://firebase.google.com/support. The Firebase Auth backend team can then review and prioritize if they feel it's a useful change.

**Comment by medvedev** [comment]
Thank you @hiranya911 
I'll go the way you suggest, i.e. create a feature request

Several refinements I'd like to share as a response to your latest comment:

>  since the password will often reach the application in the form of a web request (json or form encoded) or some other type of user input.

In Java world, password usually is stored and transmitted as array of chars

> The developer is still on the hook for not logging the password array contents,

This is not true. Array, if logged, prints object's reference ID, not array contents.

> If a memorydump is taken just before the array is cleared and that gets exposed, you still have the same problem. 

This is partially true. If I, as a developer, clear array immediately after use, I have a control over the time window, and the window's length is milliseconds, which is completely acceptable.

> One thing we can do is to provide a clear() method on the CreateRequest and UpdateRequest types

This will not address the issue, since developer still will have no control over the time of password availability in memory dump.

**Comment by hiranya911** [comment]
> In Java world, password usually is stored and transmitted as array of chars

The client could be a JS webapp or an iOS app that has its own conventions for passing data. Considering that JSON over HTTP is quite common these days, I can totally see how a client would send the password as a JSON string field to the server.

> This is not true. Array, if logged, prints object's reference ID, not array contents.

That depends on the logging framework/API one is using. If you're using the default `toString()` then you're right. But developers may have written their own utils or using 3rd party libraries that peek into the contents of arrays and containers.

> This will not address the issue, since developer still will have no control over the time of password availability in memory dump.

It does actually. After the map is cleared, the password string in memory can no longer be associated with the create/update request. It will look like any other string in the heap with no inbound references.

**Comment by hiranya911** [comment]
Based on the conversation so far and the feedback I've received from the Auth team, I'm resolving this. The risk of exposure is minimal here, and it cannot be avoided with a simple type change.
