### ISSUE TITLE
Task alive even after completion

### ISSUE THREAD

**Issue by evensocial** [firebase/firebase-admin-java#67]
`Task<Void> task = mDatabase.setValue(item);`

Even after task is completed (I'm firing an OnCompleteListener), the current thread is kept always alive.

**Comment by hiranya911** [comment]
Can you explain a bit further? What is your "current thread"? Database starts several background threads, which stay alive beyond the lifetime of request threads.

**Comment by evensocial** [comment]
Let's make it very simple. I have this code:

`public static void main(String[] args) {
	DatabaseReference mDatabase = FirebaseAdmin.getInstance().mDatabase;
	
	mDatabase.child("test-item").setValue("test");
}`

I want the main thread to end as soon as the background threads complete (i.e. The value is set on the database).
Is there a way to achieve this result?

**Comment by hiranya911** [comment]
You're encountering a known issue that is partially discussed in #55. The SDK starts a background thread, which periodically refreshes OAuth2 tokens, and in the current architecture there's no way to cleanly shut it down. It is this thread that is keeping your JVM alive, not the main application thread. This limitation will be fixed in a future release. There's some work already underway, but it will take a while to get it out. 

In the meantime I can give you a hacky workaround:
1. Call `FirebaseApp.delete()` when your application is ready to terminate. This will ensure termination of most threads.
2. Then call `FirebaseExecutors.DEFAULT_SCHEDULED_EXECUTOR.shutdownNow()` to force termination of the periodic token refresher.

In the future, you will be able to ensure termination of all threads by calling `FirebaseApp.delete()`. I'm also thinking about adding a new method to `FirebaseOptions` to provide more control over the periodic token refresher task.

**Comment by evensocial** [comment]
Thanks for your precious answer.
I'm closing this thread.
