### ISSUE TITLE
FirebaseApp.delete() still has dangling thread

### ISSUE THREAD

**Issue by nathan-ca** [firebase/firebase-admin-java#73]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Windows 10
  * Firebase SDK version: 5.3.1
  * Library version: ?
  * Firebase Product: app

### [REQUIRED] Step 3: Describe the problem

After app.delete(), there is still dangling thread. Bug can be reproduced on both 5.2.0 and latest 5.3.1 releases.

#### Steps to reproduce:

Run a trivial task, such as getUser, and call app.delete() after task complete. In my IDE, I observed three threads were created: pool-2-thread-1, pool-2-thread-2, pool-3-thread-1. After a while, pool-2-thread-[1,2] exited but pool-3-thread-1 is still dangling.

#### Relevant Code:
A trivial java test program
```
app = FirebaseApp.initializeApp(options);
Task<UserRecord> task = auth.getUser(uid);
task.addOnCompleteListener(new OnCompleteListener<UserRecord>() {

  @Override
  public void onComplete(Task<UserRecord> task) {
    app.delete();
  }
});
```

Test program won't exit after task completed.

Looks like TokenRefresher was not exiting. I have to add this hack after app.delete() call:

```
FirebaseExecutors.DEFAULT_SCHEDULED_EXECUTOR.shutdown();
```

**Comment by hiranya911** [comment]
Fix for this issue was released today: https://firebase.google.com/support/release-notes/admin/java#5.4.0

When running on the regular JVM, all threads will be started as daemons, which won't cause the process to stay alive. The `FirebaseApp.delete()` method can also be invoked to further guarantee a clean graceful shutdown (although this is not required). Proactive token refresher will not start until RTDB code is invoked.
