### ISSUE TITLE
FR: Add Support for Collections

### ISSUE THREAD

**Issue by Rossiar** [firebase/firebase-admin-java#78]
Add support to the Firebase Admin SDK for any [Collection](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html) - they all provide an [`iterator()`](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#iterator--) so I don't see why it is a problem to do this.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Microsoft Windows 10 Pro 10.0.15063
  * Firebase SDK version: 5.3.1
  * Firebase Product: realtime database

### [REQUIRED] Step 3: Describe the problem

I am trying to serialize a [Set](https://docs.oracle.com/javase/8/docs/api/java/util/Set.html) using Firebase and it is throwing `Serializing Collections is not supported, please use Lists instead` due to [this throw statement](https://github.com/firebase/firebase-admin-java/blob/master/src/main/java/com/google/firebase/database/utilities/encoding/CustomClassMapper.java#L155)

#### Steps to reproduce:

Attempt to serialize a Set with the Firebase Admin SDK

#### Relevant Code:

Here is a JUnit 4.0 test that produces the error:
```
import com.google.firebase.database.DatabaseException;
import com.google.firebase.database.utilities.encoding.CustomClassMapper;
import org.junit.Test;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertEquals;

public class FirebaseTest {

    @Test
    public void firebaseCannotSerializeSets() throws Exception {
        Map<String, Object> data = new HashMap<>();
        data.put("myset", Collections.singleton("1"));

        try {
            CustomClassMapper.convertToPlainJavaTypes(data);
        } catch (DatabaseException e) {
            assertEquals("Serializing Collections is not supported, " +
                    "please use Lists instead", e.getMessage());
        }
    }
}

```

**Comment by Rossiar** [comment]
@hiranya911 can this get some attention? I have a fork with a branch that contains the implementation for this

**Comment by hiranya911** [comment]
I'm not sure why the code is written this way. I can ask around. Please send in a pull request in any case.

**Comment by hiranya911** [comment]
@mikelehen @depoll Perhaps you guys have more context here. Any reason why we don't support serializing collections? The code is written to explicitly handle Lists.

**Comment by mikelehen** [comment]
Fundamentally, Firebase Realtime Database only supports storing Maps (key=>value pairs). We do some massaging to let you read / write arrays to Database (see [here](https://firebase.googleblog.com/2014/04/best-practices-arrays-in-firebase.html) for some details), but ultimately we just take the array and use the array indices as the keys in the Map that we ultimately store.  So in Java we let you store List because it's an ordered sequence like an array and we can use the same trick and e.g. store Arrays.asList("foo", "bar") as:
```
{
  "1": "foo"
  "2": "bar"
}
```

But collections are fundamentally unordered and so there isn't a natural mapping to the underlying Firebase RTDB data structure. We could choose to map them to an ordered list, but we chose to just avoid supporting them to avoid confusion that RTDB natively supports Sets, or other unordered collections.

So for now you'll need to convert the Collection to a List before storing.  In your example code snippet, you can just use Collections.singletonList() of course.

It's also worth noting that:

1. Our POJO mapping is bidirectional and so if we supported writing Collections, we'd also need to support reading them back and re-populating a POJO.
2. We support the same types in our admin SDK as in our Android client SDK and so if we made a change to the admin SDK, we'd want to make the same change to the Android client SDK (which unfortunately isn't open source).

**Comment by Rossiar** [comment]
@mikelehen thank you for clarifying, I was unaware that RTDB did not support arrays (I assumed a NoSQL syntax). Perhaps a small section should be added to the documentation to clarify why this is the case for Java users, could mostly be what you have said above.

**Comment by mikelehen** [comment]
No problem. I apologize for the confusion, and appreciate the time you spent on the PR.  I'll see if we can make a tweak to the docs.
