### ISSUE TITLE
Performance of the sendEach, sendEachAsync methods is too slow.

### ISSUE THREAD

**Issue by honorhs** [firebase/firebase-admin-java#941]
After updating to version 9.2.0 of the firebase-admin-java, I experienced performance issues and had to rollback to a previous version.

The performance of sendEachAsync is several to tens of times slower compared to sendAllAsync.
I don't understand why there is a decision to not provide a batch API anymore, forcing a migration to sendEach or sendEachAsync without any alternatives.
Shouldn't the SDK be provided at a reasonable level with equivalent performance?

Moreover, it does not even use HTTP/2 connections.
Why are all the performance and resource cost issues caused by SDK v9.2.0 passed onto the users?

I believe the batch API should be maintained until an alternative (API) that can match the performance of the existing batch API is developed.

I would like to hear Firebase position on this matter.

**Comment by emindeniz99** [comment]
same issues: ( and no solution yet ) :) I hope a solution before 20 june 2024 because it is the deadline for old api removal. The solution should be implemented already because developers needs sometimes to implement to their systems. There is less than 2 months.

https://github.com/firebase/firebase-admin-java/issues/834

https://github.com/firebase/firebase-admin-java/issues/849

**Comment by raychongtk** [comment]
For large-scale systems, FCM is now way too expensive for deployment cost after deprecating Batch API. In our scenario, our push notifications are intense and traffic is huge and continuous. With the new API endpoint, we found that the performance is too bad unless we deploy many machines to handle the traffic.

For this issue, I would like to know if the FCM team has any suggestions or not because not every scenario is suitable to use Topic.

**Comment by jwagun** [comment]
Any update on this performance issue?

**Comment by Kyupile** [comment]
I'm trying to apply new apis but tt has absolutely serious problem of my projects.
Compare to legacy, it costs too much seconds to get a response.
Please reply any solution except using topic.

**Comment by georgeaniljohn** [comment]
We also faced similar situation. We then moved away from firebase-admin-java SDK and have our own implementation where we use HTTP/2 and multiplexing. For now this works for us.

**Comment by honorhs** [comment]
Do you have any update on this? @lahirumaramba @jonathanedey

**Comment by moda666** [comment]
Is this issue resolved?

**Comment by xiaotuotuo321** [comment]
Is this issue resolved?

**Comment by Mzakimohammed** [comment]
👍🤗

**Comment by jonathanedey** [comment]
HTTP/2 support has now been added with the release of [v9.4.0](https://github.com/firebase/firebase-admin-java/releases/tag/v9.4.0). 
See [our wiki](https://github.com/firebase/firebase-admin-java/wiki/HTTP-Transport) for more information on this change.
